// This file is automatically generated. Do not edit it directly.
// Temporary placeholder until Supabase dependency is fixed

export const supabase = {
  auth: {
    getUser: () => Promise.resolve({ data: { user: null } }),
    signInWithOAuth: () => Promise.resolve()
  },
  from: () => ({
    select: () => ({ 
      eq: () => ({ single: () => Promise.resolve({ data: null }) }),
      limit: () => Promise.resolve({ data: null })
    }),
    upsert: () => Promise.resolve({ data: null })
  })
};